---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-yaml
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [-c, .yamllint-config.yaml]
