---
name: CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Yamllint Github Action
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_config_filepath: .yamllint-config.yaml
